# Feature Engineering Assignment - Encoding

Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you
might choose one over the other.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. Ordinal Encoding, It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. We can use Ordinal Encoding wen the values has a ranking order eg degree, while label encoding can be used when we just need to assign a numerical encoded value which does not have any rank or priorities

Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in
a machine learning project.

It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

Covariance indicates the relationship between 2 variables when one changes. If increase in one increases the other the its positve covariance, when decrease in one decreases other, its negative covariance. 

Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
Show your code and explain the output.

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Create a pandas DataFrame with the categorical variables
data = {
    'Color': ['red', 'green', 'blue', 'red', 'blue'],
    'Size': ['small', 'medium', 'large', 'medium', 'small'],
    'Material': ['wood', 'metal', 'plastic', 'wood', 'metal']
}

df = pd.DataFrame(data)

# Create a label encoder and apply it to the DataFrame
label_encoders = {}
encoded_data = pd.DataFrame()

for col in df.columns:
    print(col)
    le = LabelEncoder()
    encoded_data[col] = le.fit_transform(df[col])
    label_encoders[col] = le
print(encoded_data)

Color
Size
Material
   Color  Size  Material
0      2     2         2
1      1     1         0
2      0     0         1
3      2     1         2
4      0     2         0


Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education
level. Interpret the results.

In [5]:
import numpy as np
import pandas as pd
# Sample data for Age, Income, and Education level
data = {
    'Age': [30, 40, 35, 28, 45],
    'Income': [50000, 60000, 55000, 48000, 65000],
    'Education_Level': [12, 16, 14, 10, 18],
}
df = pd.DataFrame(data)

# Create a numpy array from the data
data_matrix = np.array([data['Age'], data['Income'], data['Education_Level']])

# Calculate the covariance matrix
cov_matrix = np.cov(data_matrix)

print(cov_matrix)
print(df.cov())

[[4.93e+01 4.93e+04 2.20e+01]
 [4.93e+04 4.93e+07 2.20e+04]
 [2.20e+01 2.20e+04 1.00e+01]]
                     Age      Income  Education_Level
Age                 49.3     49300.0             22.0
Income           49300.0  49300000.0          22000.0
Education_Level     22.0     22000.0             10.0


Q6. You are working on a machine learning project with a dataset containing several categorical
variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
each variable, and why?

For gender, we could use label encoding because it does not have an preference or ranking and also its a binary class.Education level is ordinal, meaning there's a natural order or ranking among the categories. You can assign numerical values to represent the order, such as 0 for High School, 1 for Bachelor's, 2 for Master's, and 3 for PhD. This maintains the ordinal relationship in the data.Since employment status is nominal, meaning there's no inherent order or ranking among the categories, one-hot encoding is a suitable choice. Create binary columns for each category (e.g., Unemployed, Part-Time, Full-Time) and assign 1 or 0 to indicate the presence or absence of each category.

Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two
categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
East/West). Calculate the covariance between each pair of variables and interpret the results.

In [8]:
import numpy as np

# Sample data for Temperature and Humidity
temperature = [25, 30, 35, 20, 28]
humidity = [60, 55, 70, 50, 65]

# Calculate the covariance
covariance = np.cov(temperature, humidity)[0, 1]

print("Covariance between Temperature and Humidity:", covariance)


Covariance between Temperature and Humidity: 35.0
