# Assignment Numpy

Consider the below code to answer further questions:Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [21]:
import numpy as np
list_ = list(range(1,6))
list_ = [str(i) for i in list_]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [15]:
type(array_list)

numpy.ndarray

In [16]:
type(list_)

list

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [20]:
for i in range(len(list_)):
    print(type(array_list[i]), type(list_[i]))

<class 'numpy.str_'> <class 'str'>
<class 'numpy.str_'> <class 'str'>
<class 'numpy.str_'> <class 'str'>
<class 'numpy.str_'> <class 'str'>
<class 'numpy.str_'> <class 'str'>


Q3. Considering the following changes in the variable, array_list: Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [22]:
array_list = np.array(object = list_, dtype = int)

In [23]:
array_list

array([1, 2, 3, 4, 5])

In [24]:
for i in range(len(list_)):
    print(type(array_list[i]), type(list_[i]))

<class 'numpy.int64'> <class 'str'>
<class 'numpy.int64'> <class 'str'>
<class 'numpy.int64'> <class 'str'>
<class 'numpy.int64'> <class 'str'>
<class 'numpy.int64'> <class 'str'>


The arraylist is changed to int type

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [34]:
array = np.arange(20).reshape(5,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [35]:
array.size

20

In [36]:
array.shape

(5, 4)

The size gives the no of elements in an array whereas the shape gives the num of rows and columns in any dimensional array.

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [37]:
np.zeros([3,3], dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])